<?php

/**
 * @file
 * Contains iq_multidomain_favicon_extension.module.
 */

use Drupal\file\Entity\File;

/**
 * Implements hook_page_attachments_alter().
 *
 * Alter favicon based on current domain.
 */
function iq_multidomain_sitemap_extension_page_attachments_alter(array &$attachments) {

  $domainId = \Drupal::service('domain.negotiator')->getActiveId();
  $config = \Drupal::service('config.factory')->getEditable('domain_site_settings.domainconfigsettings');
  if ($config->get($domainId . '.domain_favicon') && count($config->get($domainId . '.domain_favicon'))) {

    $file = File::load($config->get($domainId . '.domain_favicon')[0]);
    if ($file) {
      $faviconUrl = file_create_url($file->getFileUri());
      foreach ($attachments['#attached']['html_head_link'] as $index => $headLinkElement) {
        if ($headLinkElement[0]['rel'] === 'shortcut icon') {
          $attachments['#attached']['html_head_link'][$index][0]['href'] = $faviconUrl;
        }
      }
    }
  }

}
