<?php

/**
 * @file
 * Contains iq_multidomain_favicon_extension.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_config_schema_info_alter().
 *
 * Adds the favicon to the system.site mapping.
 */
function iq_multidomain_favicon_extension_config_schema_info_alter(&$definitions) {
  $definitions['system.site']['mapping']['favicon'] = [
    'type' => 'label',
    'label' => 'Favicon',
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds field for the favicon to the system_site_information_settings form.
 */
function iq_multidomain_favicon_extension_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['iq_multidomain_extensions'])) {
    $form['iq_multidomain_extensions'] = [
      '#type' => 'details',
      '#title' => t('Iqual Multidomain Settings'),
      '#open' => TRUE,
    ];
  }

  // Get the domain id from the domain name provided in the form.
  $domain_name = $form['site_information']['site_name']['#default_value'];
  $domains = \Drupal::entityTypeManager()->getStorage('domain')->loadByProperties([
    'name' => $domain_name,
  ]);
  $domain = reset($domains);
  $domain_id = $domain->id();

  $default_value = \Drupal::config('domain.config.' . $domain_id . '.system.site')->get('favicon') ?? '';

  $form['iq_multidomain_extensions']['favicon'] = [
    '#type' => 'managed_file',
    '#upload_location' => 'public://domain-favicons/',
    '#title' => t('Favicon'),
    '#default_value' => $default_value,
    '#description' => t("Custom favicon.ico for domain. If this is not set, the default favicon is used."),
    '#upload_validators' => [
      'file_validate_extensions' => ['ico'],
    ],
  ];

  // Add an additional submit handler to save
  // the favicon value to the site config.
  $form['#submit'][] = 'iq_multidomain_favicon_extension_system_site_information_settings_submit';
}

/**
 * Form submission handler.
 */
function iq_multidomain_favicon_extension_system_site_information_settings_submit(array $form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('system.site')
    ->set('favicon', $form_state->getValue('favicon'))
    ->save();
}

/**
 * Implements hook_page_attachments_alter().
 *
 * Alter favicon based on current domain.
 */
function iq_multidomain_favicon_extension_page_attachments_alter(array &$attachments) {

  $domainId = \Drupal::service('domain.negotiator')->getActiveId();
  $config = \Drupal::service('config.factory')->getEditable('domain_site_settings.domainconfigsettings');
  if ($config->get($domainId . '.domain_favicon') && (is_countable($config->get($domainId . '.domain_favicon')) ? count($config->get($domainId . '.domain_favicon')) : 0)) {

    $file = File::load($config->get($domainId . '.domain_favicon')[0]);
    if ($file) {
      $faviconUrl = $file->createFileUrl();
      foreach ($attachments['#attached']['html_head_link'] as $index => $headLinkElement) {
        if ($headLinkElement[0]['rel'] === 'icon') {
          $attachments['#attached']['html_head_link'][$index][0]['href'] = $faviconUrl;
        }
      }
    }
  }

}
