<?php

/**
 * @file
 * Contains module file.
 */

/**
 * Implements hook_theme().
 */
function iq_ui_patterns_multidomain_library_theme() {
  return [
    'patterns_overview_page' => [
      'variables' => ['patterns' => NULL],
    ],
    'patterns_single_page' => [
      'variables' => ['pattern' => NULL],
    ],
    'patterns_meta_information' => [
      'variables' => ['pattern' => NULL],
    ],
  ];
}
